;
'use strict'
const express = require('express')
const api = express.Router(),
controll = require('../controles/usuarios.control')
api.get('/prueba', controll.prueba)
api.get('/profiles', controll.getProfiles)
api.get('/findChampionship', controll.findChampionship)
api.get('/findRecord/:idChampionship', controll.findRecord)
api.get('/findProfileChampionship/:idProfileChampionship', controll.findSpecificProfileChampionship)
api.get('/getImagesPilots/:name', controll.getImagesPilots)
api.get('/findAllProfileChampionship', controll.findAllProfileChampionship)
api.get('/find-track', controll.findTrack)
api.get('/find-folders', controll.arrImages)
api.get('/find-driver', controll.findDriver)
api.get('/find-scuderia', controll.findScuderia)
api.get('/find-championship-scuderias/:championship', controll.findChampionshipScuderias)
api.get('/find-track-championship/:championship', controll.findTracksChampionship)
api.get('/find-logo-scuderia/:name', controll.getLogosScuderias)
api.get('/find-fas-lasp-championship/:id', controll.findFasLapDriverChampionship)
api.get('/find-driver-vitae-championship/:championship', controll.findDriverVitaeChampionship)
api.get('/find-championship-scuderia/:scuderia/:championship', controll.findChampionshipScuderia)
api.get('/find-championship-driver/:driver/:championship', controll.findChampionshipDriver)
api.get('/find-all-drivers-championship/:championship', controll.findPointsDriverChampionship)
api.get('/find-all-scuderias-championship/:championship', controll.findAllScuderiasChampionship)

api.post('/create-championship', controll.createChampionship)
api.post('/create-record', controll.createRecord)
api.post('/create-user', controll.createProfile)
api.post('/create-fault', controll.createFault)
api.post('/profileChampionship', controll.createProfileChampionship)
api.post('/create-track', controll.createTrack)
api.post('/create-driver', controll.createDriver)
api.post('/create-scuderia', controll.createScuderia)
api.post('/create-tracks-champuonship', controll.createTracksChampionship)
api.post('/create-scuderias-champuonship', controll.createScuderiasChampionship)
api.post('/update-champuonship', controll.updateChampionship)
api.post('/update-track', controll.updateTrack)
api.post('/update-track-championship', controll.updateTrackChampionship)
api.post('/create-driver-vitae-championship', controll.createDriverVitaeChampionship)
api.post('/create-fas-lap-driver-championship', controll.createFasLapDriverChampionship)
api.post('/update-track', controll.updateTrack),
api.post('/update-driver', controll.updateDriver)
api.post('/update-scuderia', controll.updateScuderia)
api.post('/update-scuderia-championship', controll.updateScuderiaChampionship)
api.post('/update-championship-scuderia', controll.updateChampionshipScuderia)
api.post('/update-championship-driver', controll.updateChampionshipDriver)
api.post('/create-championship-driver', controll.createChampionshipDriver)
api.post('/create-championship-scuderia', controll.createChampionshipScuderia)
module.exports = api